### ISSUE TITLE
move this._handlers to registry

### ISSUE THREAD

**Issue by giuseppeg** [flightjs/flight-with-event-proxy#1]
I think that internal implementation logic/registry stuff doesn't belong to components.
Would it make sense to move `this._handlers` to the registry?

**Comment by tgvashworth** [comment]
Hey @giuseppeg — I think we should be moving to a model where components encapsulate everything they need to bootstrap and teardown, so the registry will disappear from Flight. At the moment the registry's behaviour complects component instantiation and I'd rather get rid of it. Encapsulating the behaviour in a mixin seems like the right solution to me.

However, I don't much like `_handlers`. I'd rather namespace this kind of thing, so it's `this.withEventProxy.handlers`.

**Comment by giuseppeg** [comment]
@phuu ok I like that plan :) I suggested to move it to the registry only because those are properties on the object and therefore they are accessible from within the component

**Comment by ahume** [comment]
Thoughts on a good pattern for exposing the mixin methods on the `eventProxy` namespace? Requirements are it should preserve `this` as the component in a sensible way, not have to bind every function, and ideally not have to repeat the namespace all over the place.

**Comment by tgvashworth** [comment]
Maybe the methods could be left directly on `this` but the data is kept under the namespace and created once per instance of the component (perhaps before initialize)?
